version: '2'
services:
  proxy:
    image: oconnormi/karaf:4.0
    ports:
      - "8181:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./proxy/configure.sh:/app/entrypoint/configure.sh
    links:
      - node1
      - node2
    entrypoint: /app/entrypoint/entrypoint.sh
  node1:
    image: oconnormi/karaf:4.0
    ports:
      - "8182:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./nodes/configure.sh:/app/entrypoint/configure.sh
    entrypoint: /app/entrypoint/entrypoint.sh
  node2:
    image: oconnormi/karaf:4.0
    ports:
      - "8183:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./nodes/configure.sh:/app/entrypoint/configure.sh
    entrypoint: /app/entrypoint/entrypoint.sh
