version: '2'
services:
  load-balancer:
    image: oconnormi/karaf:4.0
    ports:
      - "8181:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./load-balancer/configure.sh:/app/entrypoint/configure.sh
      - ./load-balancer/etc/org.apache.karaf.cellar.node.cfg:/app/etc/org.apache.karaf.cellar.node.cfg
      - ./load-balancer/etc/org.apache.karaf.cellar.groups.cfg:/app/etc/org.apache.karaf.cellar.groups.cfg
    links:
      - karaf1
      - karaf2
    entrypoint: /app/entrypoint/entrypoint.sh
  karaf1:
    image: oconnormi/karaf:4.0
    ports:
      - "8182:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./nodes/configure.sh:/app/entrypoint/configure.sh
      - ./nodes/etc/org.apache.karaf.cellar.node.cfg:/app/etc/org.apache.karaf.cellar.node.cfg
    entrypoint: /app/entrypoint/entrypoint.sh
  karaf2:
    image: oconnormi/karaf:4.0
    ports:
      - "8183:8181"
    volumes:
      - ./nodes/deploy/:/app/deploy
      - ./nodes/entrypoint.sh:/app/entrypoint/entrypoint.sh
      - ./nodes/configure.sh:/app/entrypoint/configure.sh
      - ./nodes/etc/org.apache.karaf.cellar.node.cfg:/app/etc/org.apache.karaf.cellar.node.cfg
    entrypoint: /app/entrypoint/entrypoint.sh
